services:
  app:
    image: quiver-to-obsidian-exporter
    build: 
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./testdata:/app/testdata
    command: tail -f /dev/null
    environment:
      QUIVER_TO_OBSIDIAN_EXPORTER_LOGGING_VERBOSE: false